
import React, { useState, useEffect } from 'react';
import { 
  Clock, 
  CheckCircle2, 
  Zap,
  Save,
  MonitorPlay,
  AlertCircle,
  Mail,
  Power,
  PowerOff,
  X,
  Check,
  PlaneTakeoff,
  Octagon,
  FileText,
  CheckCheck,
  UserCircle,
  ChevronDown
} from 'lucide-react';
import { ShiftType, TeamLeader, ProductionEntry, HourlyEntry, ProductionLine } from '../types';

interface ShiftBoardsProps {
  leaders: TeamLeader[];
  onSaveReport: (report: ProductionEntry) => void;
  onUpdateLeader: (leader: TeamLeader) => void;
}

const ShiftBoards: React.FC<ShiftBoardsProps> = ({ leaders, onSaveReport, onUpdateLeader }) => {
  const [activeShift, setActiveShift] = useState<ShiftType>(ShiftType.MORNING);
  
  const [shiftLeaderAssignments, setShiftLeaderAssignments] = useState<Record<ShiftType, string>>({
    [ShiftType.MORNING]: leaders[0]?.id || '',
    [ShiftType.EVENING]: leaders[1]?.id || '',
    [ShiftType.NIGHT]: leaders[2]?.id || ''
  });

  const [isReportingStoppage, setIsReportingStoppage] = useState(false);
  const [stoppageForm, setStoppageForm] = useState<{
    reason: string;
    returnDate: string;
    type: 'on_leave' | 'stopped';
  }>({ reason: '', returnDate: '', type: 'on_leave' });

  useEffect(() => {
    setShiftLeaderAssignments(prev => {
      const next = { ...prev };
      Object.keys(next).forEach(shift => {
        if (!leaders.find(l => l.id === next[shift as ShiftType])) {
           next[shift as ShiftType] = leaders[0]?.id || '';
        }
      });
      return next;
    });
  }, [leaders]);

  const createInitialData = () => Array.from({ length: 8 }, (_, i) => ({
    hour: i + 1,
    reference: '', 
    target: 70, 
    actual: 0,
    rejects: 0,
    note: ''
  }));

  const [hourlyStates, setHourlyStates] = useState<Record<ShiftType, Record<ProductionLine, HourlyEntry[]>>>({
    [ShiftType.MORNING]: {
      [ProductionLine.LINE_1]: createInitialData(),
      [ProductionLine.LINE_2]: createInitialData(),
      [ProductionLine.LINE_3]: createInitialData()
    },
    [ShiftType.EVENING]: {
      [ProductionLine.LINE_1]: createInitialData(),
      [ProductionLine.LINE_2]: createInitialData(),
      [ProductionLine.LINE_3]: createInitialData()
    },
    [ShiftType.NIGHT]: {
      [ProductionLine.LINE_1]: createInitialData(),
      [ProductionLine.LINE_2]: createInitialData(),
      [ProductionLine.LINE_3]: createInitialData()
    }
  });

  const handleUpdateHour = (shift: ShiftType, line: ProductionLine, hourIdx: number, field: keyof HourlyEntry, value: any) => {
    setHourlyStates(prev => ({
      ...prev,
      [shift]: {
        ...prev[shift],
        [line]: prev[shift][line].map((h, i) => i === hourIdx ? { ...h, [field]: value } : h)
      }
    }));
  };

  const getLeaderForShift = (shift: ShiftType) => {
    const leaderId = shiftLeaderAssignments[shift];
    return leaders.find(l => l.id === leaderId) || leaders[0];
  };

  const calculateLineTotals = (shift: ShiftType, line: ProductionLine) => {
    const data = hourlyStates[shift][line];
    const actual = data.reduce((acc, cur) => acc + (Number(cur.actual) || 0), 0);
    const target = data.reduce((acc, cur) => acc + (Number(cur.target) || 0), 0);
    const rejects = data.reduce((acc, cur) => acc + (Number(cur.rejects) || 0), 0);
    const efficiency = target > 0 ? Math.round((actual / target) * 100) : 0;
    return { actual, target, rejects, efficiency };
  };

  const shareSummaryViaEmail = (shift: ShiftType) => {
    const leader = getLeaderForShift(shift);
    const subject = `Production Report: ${shift} Shift - 7.67H Trace`;
    let body = `Production Report ${shift} Shift (7.67H Trace)\n`;
    body += `Leader: ${leader.name}\n`;
    body += `--------------------------\n`;

    [ProductionLine.LINE_1, ProductionLine.LINE_2, ProductionLine.LINE_3].forEach(line => {
      const totals = calculateLineTotals(shift, line);
      body += `${line}:\n`;
      body += `Total: ${totals.actual} | Efficiency: ${totals.efficiency}%\n\n`;
    });

    body += `Generated by ProTrack AI`;
    window.location.href = `mailto:${leader.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const performSaveLineReport = (shift: ShiftType, line: ProductionLine) => {
    const totals = calculateLineTotals(shift, line);
    const leader = getLeaderForShift(shift);
    const report: ProductionEntry = {
      id: `${Date.now()}-${shift}-${line}-${Math.random().toString(36).substr(2, 5)}`,
      shift,
      date: new Date().toISOString().split('T')[0],
      lineId: line,
      leaderId: leader.id,
      hourlyData: [...hourlyStates[shift][line]],
      totalOutput: totals.actual,
      totalTarget: totals.target,
      totalRejects: totals.rejects,
      efficiency: totals.efficiency
    };
    onSaveReport(report);
  };

  const saveLineReport = (shift: ShiftType, line: ProductionLine) => {
    performSaveLineReport(shift, line);
    alert(`Report for ${line} saved for ${shift} shift under supervisor ${getLeaderForShift(shift).name}.`);
  };

  const saveAllReports = () => {
    let savedCount = 0;
    Object.values(ShiftType).forEach(shift => {
      Object.values(ProductionLine).forEach(line => {
        performSaveLineReport(shift, line);
        savedCount++;
      });
    });
    alert(`${savedCount} full reports (all lines & shifts) archived successfully.`);
  };

  const currentLeader = getLeaderForShift(activeShift);

  return (
    <div className="space-y-12 animate-in fade-in duration-1000">
      <div className="bg-white p-10 rounded-[3.5rem] border border-slate-100 shadow-sm flex flex-col xl:flex-row justify-between items-center gap-6 relative overflow-hidden">
        <div className="relative z-10">
          <div className="flex items-center gap-4 mb-2">
            <div className="w-2 h-8 bg-orange-500 rounded-full"></div>
            <h2 className="text-4xl font-black text-slate-900 tracking-tighter uppercase leading-none">Production Monitoring</h2>
          </div>
          <p className="text-orange-600 text-[10px] font-black uppercase tracking-[0.4em] pl-6">Assignment tracking for lines 1, 2 & 3</p>
        </div>
        
        <div className="flex flex-col sm:flex-row items-center gap-4 relative z-10">
          <button 
            onClick={saveAllReports}
            className="flex items-center gap-3 bg-slate-900 hover:bg-orange-500 text-white px-8 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest shadow-xl shadow-slate-100 transition-all active:scale-95"
          >
            <CheckCheck size={18} />
            <span>Archive All Data</span>
          </button>

          <div className="flex bg-slate-50 p-2 rounded-2xl border border-slate-200">
            {[ShiftType.MORNING, ShiftType.EVENING, ShiftType.NIGHT].map(s => (
              <button 
                key={s}
                onClick={() => setActiveShift(s)}
                className={`px-8 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest transition-all ${activeShift === s ? 'bg-white text-orange-600 shadow-md border border-orange-50' : 'text-slate-400 hover:text-orange-500'}`}
              >
                {s}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-10 items-start">
        <div className="xl:col-span-1 sticky top-28 space-y-8">
          <div className="bg-white rounded-[3.5rem] border border-slate-100 p-8 shadow-sm flex flex-col items-center text-center">
            <div className="w-32 h-32 rounded-[2rem] overflow-hidden border-4 border-orange-50 shadow-xl mb-6 group relative">
              <img src={currentLeader.imageUrl} className={`w-full h-full object-cover transition-transform group-hover:scale-110 ${currentLeader.status === 'active' ? '' : 'grayscale'}`} alt="Leader" />
            </div>
            
            <div className="w-full space-y-4 mb-6">
               <div className="flex flex-col items-center">
                 <span className="text-orange-600 text-[8px] font-black uppercase tracking-[0.3em] mb-2">Active Shift Leader</span>
                 <div className="relative w-full">
                    <select 
                      value={shiftLeaderAssignments[activeShift]}
                      onChange={(e) => setShiftLeaderAssignments(prev => ({ ...prev, [activeShift]: e.target.value }))}
                      className="w-full bg-slate-50 border border-slate-200 pl-4 pr-10 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest appearance-none outline-none focus:border-orange-500 text-center"
                    >
                      {leaders.map(l => (
                        <option key={l.id} value={l.id}>{l.name}</option>
                      ))}
                    </select>
                    <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                 </div>
               </div>
            </div>

            <div className="flex gap-2">
               {currentLeader.status === 'active' ? (
                 <button onClick={() => setIsReportingStoppage(true)} className="flex items-center gap-2 bg-red-50 text-red-500 px-4 py-2 rounded-xl text-[10px] font-black uppercase border border-red-100">
                    <PowerOff size={14} /> Stop
                 </button>
               ) : (
                 <button onClick={() => onUpdateLeader({ ...currentLeader, status: 'active' })} className="flex items-center gap-2 bg-green-50 text-green-500 px-4 py-2 rounded-xl text-[10px] font-black uppercase border border-green-100">
                    <Power size={14} /> Resume
                 </button>
               )}
            </div>
          </div>

          <div className="bg-orange-500 rounded-[2.5rem] p-8 text-white shadow-lg shadow-orange-100 space-y-4">
             <div className="text-center mb-4">
                <span className="text-[10px] font-black uppercase tracking-widest opacity-80">Shift Tracking Goal</span>
                <p className="text-4xl font-black tracking-tighter">7.67 H</p>
             </div>
             <button onClick={() => shareSummaryViaEmail(activeShift)} className="w-full bg-white text-orange-600 py-4 rounded-xl font-black text-[10px] uppercase tracking-widest flex items-center justify-center gap-3 hover:scale-105 transition-all shadow-md">
                <Mail size={16} /> Send via Email
             </button>
          </div>
        </div>

        <div className="xl:col-span-3 space-y-12">
          {[ProductionLine.LINE_1, ProductionLine.LINE_2, ProductionLine.LINE_3].map((line) => {
             const totals = calculateLineTotals(activeShift, line);
             return (
               <div key={line} className="bg-white rounded-[3.5rem] border border-slate-100 shadow-sm overflow-hidden">
                  <div className="p-8 border-b border-slate-50 flex flex-col md:flex-row justify-between items-center gap-6">
                    <div className="flex items-center gap-4">
                      <div className="p-3 bg-orange-50 text-orange-500 rounded-xl"><MonitorPlay size={20} /></div>
                      <div>
                        <h3 className="text-xl font-black text-slate-900 tracking-tighter uppercase leading-none">{line}</h3>
                        <p className="text-orange-600 text-[8px] font-black uppercase mt-1">Real-time Performance Metrics</p>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-8">
                       <div className="text-center">
                          <span className="text-[8px] font-black text-slate-400 uppercase block">Actual</span>
                          <span className="text-xl font-black text-slate-900">{totals.actual}</span>
                       </div>
                       <div className="text-center">
                          <span className="text-[8px] font-black text-slate-400 uppercase block">Target</span>
                          <span className="text-xl font-bold text-slate-400">{totals.target}</span>
                       </div>
                       <div className="text-center">
                          <span className="text-[8px] font-black text-slate-400 uppercase block">Efficiency</span>
                          <span className="text-xl font-black text-orange-600">{totals.efficiency}%</span>
                       </div>
                       <button 
                         onClick={() => saveLineReport(activeShift, line)}
                         className="p-3 bg-orange-50 text-orange-600 hover:bg-orange-500 hover:text-white rounded-xl transition-all shadow-sm border border-orange-100"
                         title="Save Report"
                       >
                         <Save size={20} />
                       </button>
                    </div>
                  </div>

                  <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="bg-slate-50/50 text-slate-400 text-[10px] font-black uppercase tracking-widest border-b border-slate-50">
                          <th className="p-6 text-center w-20">Hour</th>
                          <th className="p-6 text-center w-32">Ref (Batch)</th>
                          <th className="p-6 text-center w-24">Target</th>
                          <th className="p-6 text-center w-32">Produced</th>
                          <th className="p-6 text-center w-24">Rejects</th>
                          <th className="p-6">Notes</th>
                          <th className="p-6 text-center w-20">Status</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-50">
                        {hourlyStates[activeShift][line].map((entry, idx) => (
                          <tr key={idx} className="hover:bg-orange-50/10 transition-all">
                            <td className="p-6 text-center">
                              <div className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-slate-100 text-slate-900 font-black text-[10px]">
                                {idx + 1}
                              </div>
                            </td>
                            <td className="p-6 text-center">
                              <div className="flex items-center gap-2 bg-slate-50 border border-slate-100 rounded-xl px-3 py-2">
                                <FileText size={14} className="text-slate-300" />
                                <input 
                                  className="w-full bg-transparent text-[10px] font-black uppercase outline-none placeholder:text-slate-200"
                                  placeholder="REF-XXXX"
                                  value={entry.reference}
                                  onChange={(e) => handleUpdateHour(activeShift, line, idx, 'reference', e.target.value)}
                                />
                              </div>
                            </td>
                            <td className="p-6 text-center">
                              <input 
                                type="number"
                                className="w-16 bg-white border border-slate-100 p-2 rounded-xl text-center font-black text-slate-400 focus:border-orange-500 outline-none"
                                value={entry.target || ''}
                                onChange={(e) => handleUpdateHour(activeShift, line, idx, 'target', parseInt(e.target.value) || 0)}
                              />
                            </td>
                            <td className="p-6 text-center">
                              <input 
                                type="number"
                                className="w-20 bg-white border border-slate-200 p-3 rounded-xl text-center font-black text-orange-600 focus:border-orange-500 outline-none"
                                value={entry.actual || ''}
                                onChange={(e) => handleUpdateHour(activeShift, line, idx, 'actual', parseInt(e.target.value) || 0)}
                              />
                            </td>
                            <td className="p-6 text-center">
                              <input 
                                type="number"
                                className="w-16 bg-white border border-slate-100 p-3 rounded-xl text-center font-black text-red-300 focus:border-red-500 outline-none"
                                value={entry.rejects || ''}
                                onChange={(e) => handleUpdateHour(activeShift, line, idx, 'rejects', parseInt(e.target.value) || 0)}
                              />
                            </td>
                            <td className="p-6">
                              <input 
                                className="w-full bg-slate-50 border border-slate-50 p-3 rounded-xl text-xs font-bold outline-none focus:bg-white focus:border-orange-100"
                                placeholder="..."
                                value={entry.note}
                                onChange={(e) => handleUpdateHour(activeShift, line, idx, 'note', e.target.value)}
                              />
                            </td>
                            <td className="p-6 text-center">
                              {entry.actual >= entry.target && entry.target > 0 ? (
                                <CheckCircle2 size={16} className="text-green-500 inline" />
                              ) : entry.actual > 0 ? (
                                <Zap size={16} className="text-orange-500 inline animate-pulse" />
                              ) : (
                                <AlertCircle size={16} className="text-slate-200 inline" />
                              )}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
               </div>
             );
          })}
        </div>
      </div>
    </div>
  );
};

export default ShiftBoards;
